export const teamOptions = [
  'AI Tiger Team',
  'BDC-Seven Bridges',
  'BioData Catalyst Coordinating Center (BDC3)',
  'CONNECTS',
  'COPDGene',
  'Data Management Core (DMC)',
  'Dug',
  'External Expert Panel',
  'Fellows',
  'Gen3',
  'Geneial',
  'ITAC',
  'Kids First',
  'NIH/NHLBI',
  'PIC-SURE',
  'SC User Community Rep',
  'Terra',
  'TOPMed',
  'University of Michigan',
  'Verily',
];

export const affiliationOptions = [
  'Albert Einstein College of Medicine',
  'Atlanta University Center Consortium',
  "Brigham and Women's Hospital",
  'Broad Institute',
  'Case Western Reserve University',
  "Children's Hospital of Philadelphia",
  'Cold Spring Harbor Laboratory',
  'Duke University',
  'Elsevier',
  'Geneial',
  'Harvard Medical School',
  'Harvard University',
  'Howard University',
  'Icahn School of Medicine at Mount Sinai Hospital',
  'Institute for Systems Biology',
  'Isomics Inc.',
  'Joslin Diabetes Center',
  'Lawrence Berkeley National Laboratory',
  'Massachusetts General Hospital',
  'Medical University of South Carolina',
  'Missouri University of Science & Technology',
  'National Jewish Health',
  'New Jersey Institute of Technology',
  'New York University School of Global Health',
  'NIH/NCI',
  'NIH/NHLBI',
  'Nimbus Informatics',
  'Oregon State University',
  'Radical Imaging',
  'Renaissance Computing Institute (RENCI)',
  'Repositive',
  'RTI International',
  'Stanford University',
  'The Jackson Laboratory',
  'The Mount Sinai Health System',
  'The University of Manchester',
  'UK Biobank',
  'University of Alabama at Birmingham',
  'University of California - Santa Cruz',
  'University of Chicago',
  'University of Colorado',
  'University of Colorado Anschutz Medical Campus',
  'University of Colorado Denver',
  'University of Illinois at Chicago',
  'University of Kansas Medical Center Research Institute, Inc.',
  'University of Kentucky',
  'University of Michigan',
  'University of New Mexico Health Sciences Center',
  'University of North Carolina at Chapel Hill',
  'University of Pennsylvania',
  'University of Texas Health Science Center at Houston',
  'University of Utah',
  'University of Washington',
  'University of Wisconsin',
  'US Department of Veterans Affairs',
  'Vanderbilt University',
  'Vanderbilt University Medical Center',
  'Velsera',
  'Verily',
];

export const projectRoleOptions = [
  'BioData Catalyst Consortium Member',
  'BioData Catalyst Program Officer',
  'Co-Investigator',
  'Data Management Core Collaborator',
  'Data Steward',
  'Developer',
  'Executive Assistant',
  'External Collaborator',
  'External Expert',
  'Fellow Alumni',
  'Fellows',
  'Institution Lead',
  'OT Office',
  'Principal Investigator',
  'Project Manager',
  'Steering Committee Chair',
  'Technical Lead',
];

export const collaborationGroups = [
  'Architecture WG / Team Collaboration Meeting',
  'Change Control Board (CCB)',
  'Consortium Collaboration Meeting (CCM)',
  'Data Release Management Working Group (DRMWG)',
  'RECOVER at BDC',
];
